import { UserProfile, StudentStats, WeakTopicItem } from '../types';
import { getTodayDateString, getOffsetDateString } from '../utils/streakManager';

export const DEFAULT_USERS: UserProfile[] = [
  {
    id: 'user-ritik',
    name: 'Ritik Pal',
    email: 'ritik.pal7905@gmail.com',
    password: 'password123',
    avatarInitials: 'RP',
    academicLevel: 'Undergraduate',
    majorOrFocus: 'Computer Science & AI',
    targetGoal: 'Upcoming Semester Exams & Competitive Algorithmic Mastery',
    organization: 'Apex Coaching Institute',
    role: 'student',
    joinedDate: 'September 2026',
    streakDetails: {
      lastVisitDate: getTodayDateString(),
      lastPracticeDate: getTodayDateString(),
      visitedDates: [0, 1, 2, 3, 4, 5, 6, 7, 8].map(getOffsetDateString),
      practicedDates: [0, 1, 2, 3, 4, 5, 6].map(getOffsetDateString),
      currentStreak: 9,
      longestStreak: 12,
    },
    stats: {
      studyStreakDays: 9,
      weeklyHoursStudied: 22.5,
      doubtsResolvedCount: 14,
      quizzesCompletedCount: 9,
      averageQuizScore: 89,
      conceptMastery: [
        { subject: 'Computer Science & AI', score: 86, color: '#6366f1' },
        { subject: 'Mathematics & Statistics', score: 82, color: '#8b5cf6' },
        { subject: 'Physics & Engineering', score: 74, color: '#06b6d4' },
        { subject: 'Economics & Business', score: 88, color: '#10b981' },
      ],
      recentActivities: [
        {
          id: 'act-r1',
          type: 'guide',
          title: 'Weakness Diagnostic: Dynamic Programming',
          date: '10 mins ago',
          highlight: 'Diagnosed subproblem memoization & boundary state traps',
        },
        {
          id: 'act-r2',
          type: 'quiz',
          title: 'Algorithms: Graph Shortest Paths',
          date: 'Yesterday',
          highlight: 'Scored 5/5 (100%)',
        },
        {
          id: 'act-r3',
          type: 'doubt',
          title: 'P vs NP intuitive limits',
          date: '2 days ago',
          highlight: 'Deconstructed deterministic polynomial verification',
        },
      ],
    },
    weakTopics: [
      {
        id: 'wt-r-1',
        topicName: 'Dynamic Programming: State Space & Tabulation Optimization',
        subject: 'Computer Science & AI',
        severity: 'Critical Gap',
        masteryScore: 54,
        rootCause: 'Struggling to differentiate optimal substructure from greedy choices, and managing 1D rolling array boundary transitions.',
        actionableSuggestions: [
          'Draw the recursion DAG for small inputs (n=3, 4) before writing code.',
          'Convert recursive solutions into 2D tables to observe row dependencies.',
          'Use the 3-step formula: 1) State definition, 2) Transition formula, 3) Base cases.'
        ],
        keyPitfallToAvoid: 'Jumping straight into writing nested loops before formulating the formal recurrence relation.',
        quickCheckQuestion: 'In the 0/1 Knapsack problem, why does the inner weight loop run backward in a 1D space-optimized array?',
        recommendedStudyTime: '45 mins / day for 3 days',
        status: 'Practicing',
      },
      {
        id: 'wt-r-2',
        topicName: 'Integration by Parts: Algebraic Sign Distribution & LIATE',
        subject: 'Mathematics & Statistics',
        severity: 'Critical Gap',
        masteryScore: 58,
        rootCause: 'Sign-flipping errors during repeated integration and misidentifying which subfunction to assign to u vs dv using LIATE.',
        actionableSuggestions: [
          'Apply the LIATE rule systematically before assigning u and dv.',
          'Use the Tabular Method for polynomial-exponential products.',
          'Differentiate your resulting antiderivative to verify it reproduces the integrand.'
        ],
        keyPitfallToAvoid: 'Forgetting the negative sign distribution across multi-step nested integration terms.',
        quickCheckQuestion: 'When evaluating ∫ e^x * sin(x) dx, what recursive algebraic technique is required to isolate the integral?',
        recommendedStudyTime: '30 mins / day for 4 days',
        status: 'Under Review',
      },
      {
        id: 'wt-r-3',
        topicName: 'Distributed Consensus: Raft Log Invariants & Leader Election',
        subject: 'Computer Science & AI',
        severity: 'Moderate Difficulty',
        masteryScore: 68,
        rootCause: 'Confusion regarding split-vote split brain mitigation and log matching property verification during network partitions.',
        actionableSuggestions: [
          'Simulate the 3-node election timeout with randomized randomized countdown timers.',
          'Review the Raft state machine safety invariant: leader append-only constraint.',
          'Trace log compaction and snapshot mechanisms.'
        ],
        keyPitfallToAvoid: 'Assuming majority quorum means unanimous agreement across all partitioned nodes.',
        quickCheckQuestion: 'Why does Raft require randomized election timeouts between 150ms and 300ms?',
        recommendedStudyTime: '30 mins / day for 2 days',
        status: 'Practicing',
      }
    ],
  },
  {
    id: 'user-alex',
    name: 'Alex Rivera',
    email: 'alex.rivera@studymate.edu',
    password: 'password123',
    avatarInitials: 'AR',
    academicLevel: 'Undergraduate',
    majorOrFocus: 'Computer Science & AI',
    targetGoal: 'FAANG Technical Interviews & System Architecture',
    organization: 'Apex Coaching Institute',
    role: 'student',
    joinedDate: 'August 2026',
    streakDetails: {
      lastVisitDate: getTodayDateString(),
      lastPracticeDate: getOffsetDateString(1),
      visitedDates: [0, 1, 2, 3, 4, 5, 6].map(getOffsetDateString),
      practicedDates: [1, 2, 3, 4, 5].map(getOffsetDateString),
      currentStreak: 7,
      longestStreak: 10,
    },
    stats: {
      studyStreakDays: 7,
      weeklyHoursStudied: 18.5,
      doubtsResolvedCount: 11,
      quizzesCompletedCount: 7,
      averageQuizScore: 84,
      conceptMastery: [
        { subject: 'Computer Science & AI', score: 81, color: '#6366f1' },
        { subject: 'Mathematics & Statistics', score: 76, color: '#8b5cf6' },
        { subject: 'Physics & Engineering', score: 68, color: '#06b6d4' },
      ],
      recentActivities: [
        {
          id: 'act-a1',
          type: 'tutor',
          title: 'System Design: Cache Invalidation Strategies',
          date: '3 hours ago',
          highlight: 'Analyzed write-through vs write-back latency bounds',
        },
      ],
    },
    weakTopics: [
      {
        id: 'wt-a-1',
        topicName: 'Graph Cycle Invariants & Disjoint Set Union (DSU)',
        subject: 'Computer Science & AI',
        severity: 'Critical Gap',
        masteryScore: 56,
        rootCause: 'Forgetting path compression and union-by-rank amortized alpha(N) time complexities.',
        actionableSuggestions: [
          'Code find() with recursive root assignment to master path compression.',
          'Practice Kruskal minimum spanning tree implementations on undirected graphs.',
        ],
        keyPitfallToAvoid: 'Calling union without first evaluating the root parents of both elements.',
        quickCheckQuestion: 'What is the Ackermann inverse alpha(N) value for all practical universe sizes?',
        recommendedStudyTime: '35 mins / day for 2 days',
        status: 'Under Review',
      },
      {
        id: 'wt-a-2',
        topicName: 'Eigenvalue Decomposition & Spectral Theorem',
        subject: 'Mathematics & Statistics',
        severity: 'Moderate Difficulty',
        masteryScore: 66,
        rootCause: 'Geometric vs algebraic multiplicity confusion in non-diagonalizable matrices.',
        actionableSuggestions: [
          'Plot the transformation of unit circles into ellipses to visualize singular vectors.',
          'Verify det(A - lambda*I) = 0 systematically.',
        ],
        keyPitfallToAvoid: 'Assuming all square matrices have a full set of orthogonal eigenvectors.',
        quickCheckQuestion: 'Under what condition is a real square matrix guaranteed to be orthogonally diagonalizable?',
        recommendedStudyTime: '30 mins / day for 3 days',
        status: 'Practicing',
      }
    ],
  },
  {
    id: 'user-sophia',
    name: 'Sophia Chen',
    email: 'sophia.chen@studymate.edu',
    password: 'password123',
    avatarInitials: 'SC',
    academicLevel: 'Pre-Med Undergraduate',
    majorOrFocus: 'Biology & Medicine',
    targetGoal: 'MCAT Preparation & Biochemistry Honors',
    organization: 'Stanford Pre-Med Academy',
    role: 'student',
    joinedDate: 'July 2026',
    streakDetails: {
      lastVisitDate: getTodayDateString(),
      lastPracticeDate: getTodayDateString(),
      visitedDates: Array.from({ length: 14 }, (_, i) => getOffsetDateString(i)),
      practicedDates: Array.from({ length: 12 }, (_, i) => getOffsetDateString(i)),
      currentStreak: 14,
      longestStreak: 18,
    },
    stats: {
      studyStreakDays: 14,
      weeklyHoursStudied: 26.0,
      doubtsResolvedCount: 19,
      quizzesCompletedCount: 12,
      averageQuizScore: 92,
      conceptMastery: [
        { subject: 'Biology & Medicine', score: 94, color: '#10b981' },
        { subject: 'Chemistry', score: 88, color: '#f59e0b' },
        { subject: 'Mathematics & Statistics', score: 80, color: '#8b5cf6' },
      ],
      recentActivities: [
        {
          id: 'act-s1',
          type: 'quiz',
          title: 'Enzyme Kinetics & Lineweaver-Burk Plots',
          date: 'Yesterday',
          highlight: 'Scored 5/5 (100%)',
        },
      ],
    },
    weakTopics: [
      {
        id: 'wt-s-1',
        topicName: 'CRISPR-Cas9 PAM Recognition & Repair Pathways',
        subject: 'Biology & Medicine',
        severity: 'Moderate Difficulty',
        masteryScore: 71,
        rootCause: 'Mixing up homology-directed repair (HDR) requirements with error-prone NHEJ knockouts.',
        actionableSuggestions: [
          'Diagram the Cas9 R-loop formation and PAM interrogation sequence step-by-step.',
          'Contrast cell cycle phases where HDR is active (S/G2) vs NHEJ (all phases).'
        ],
        keyPitfallToAvoid: 'Assuming Cas9 can cleave DNA without first recognizing the adjacent PAM motif.',
        quickCheckQuestion: 'What triggers NHEJ over HDR when double-strand breaks occur during G1 phase?',
        recommendedStudyTime: '25 mins / day for 2 days',
        status: 'Under Review',
      },
      {
        id: 'wt-s-2',
        topicName: 'Buffer Systems & Henderson-Hasselbalch Equilibria',
        subject: 'Chemistry',
        severity: 'Needs Polish',
        masteryScore: 79,
        rootCause: 'Using molarity rather than mole ratios during strong acid/base titration stress.',
        actionableSuggestions: [
          'Use ICE tables in moles before applying pH = pKa + log([A-]/[HA]).',
          'Remember optimal buffer capacity occurs when pH = pKa.'
        ],
        keyPitfallToAvoid: 'Applying the equation after buffer capacity has been exceeded.',
        quickCheckQuestion: 'At what ratio of [A-] to [HA] is a buffer most resistant to pH shifts?',
        recommendedStudyTime: '20 mins / day for 2 days',
        status: 'Mastered',
      }
    ],
  },
  {
    id: 'user-liam',
    name: 'Liam Vance',
    email: 'liam.vance@studymate.edu',
    password: 'password123',
    avatarInitials: 'LV',
    academicLevel: 'Undergraduate',
    majorOrFocus: 'Physics & Engineering',
    targetGoal: 'Mastering Classical Mechanics & Maxwell Equations',
    organization: 'NA', // Individual learner without institution affiliation
    role: 'student',
    joinedDate: 'September 2026',
    streakDetails: {
      lastVisitDate: getTodayDateString(),
      lastPracticeDate: getOffsetDateString(1),
      visitedDates: [0, 1, 2, 3, 4].map(getOffsetDateString),
      practicedDates: [1, 2, 3, 4].map(getOffsetDateString),
      currentStreak: 5,
      longestStreak: 8,
    },
    stats: {
      studyStreakDays: 5,
      weeklyHoursStudied: 15.0,
      doubtsResolvedCount: 8,
      quizzesCompletedCount: 5,
      averageQuizScore: 81,
      conceptMastery: [
        { subject: 'Physics & Engineering', score: 80, color: '#06b6d4' },
        { subject: 'Mathematics & Statistics', score: 85, color: '#8b5cf6' },
      ],
      recentActivities: [
        {
          id: 'act-l1',
          type: 'doubt',
          title: 'Inductor current inertia vs capacitor voltage',
          date: 'Yesterday',
          highlight: 'Mapped magnetic flux linkage back to Faraday EMF',
        },
      ],
    },
    weakTopics: [
      {
        id: 'wt-l-1',
        topicName: 'Rotational Dynamics & Angular Momentum Conservation',
        subject: 'Physics & Engineering',
        severity: 'Critical Gap',
        masteryScore: 61,
        rootCause: 'Failing to determine the correct axis of rotation when calculating moments of inertia, and confusing net torque with linear force.',
        actionableSuggestions: [
          'State chosen pivot point explicitly before setting Sigma tau = I alpha.',
          'Review Parallel Axis Theorem (I = I_cm + Md^2) with rolling cylinders.',
          'Map linear analogs directly: m <-> I, v <-> omega, F <-> tau, p <-> L.'
        ],
        keyPitfallToAvoid: 'Assuming angular momentum is conserved about ANY point when an external torque exists.',
        quickCheckQuestion: 'Why does an ice skater spin faster when pulling in their arms?',
        recommendedStudyTime: '35 mins / day for 3 days',
        status: 'Practicing',
      }
    ],
  },
  {
    id: 'user-faculty-vikram',
    name: 'Prof. Vikram Sharma',
    email: 'vikram.sharma@apexacademy.edu',
    password: 'password123',
    avatarInitials: 'VS',
    academicLevel: 'Faculty & Department Head',
    majorOrFocus: 'Computer Science & AI',
    targetGoal: 'Batch Cognitive Diagnostic Tracking & Offline Remedial Interventions',
    organization: 'Apex Coaching Institute',
    role: 'faculty',
    joinedDate: 'January 2026',
    streakDetails: {
      lastVisitDate: getTodayDateString(),
      lastPracticeDate: getTodayDateString(),
      visitedDates: Array.from({ length: 20 }, (_, i) => getOffsetDateString(i)),
      practicedDates: Array.from({ length: 18 }, (_, i) => getOffsetDateString(i)),
      currentStreak: 20,
      longestStreak: 25,
    },
    stats: {
      studyStreakDays: 20,
      weeklyHoursStudied: 32.0,
      doubtsResolvedCount: 45,
      quizzesCompletedCount: 18,
      averageQuizScore: 98,
      conceptMastery: [
        { subject: 'Computer Science & AI', score: 98, color: '#6366f1' },
        { subject: 'Mathematics & Statistics', score: 95, color: '#8b5cf6' },
      ],
      recentActivities: [
        {
          id: 'act-f1',
          type: 'guide',
          title: 'Cohort Diagnostics: Dynamic Programming Gaps Reviewed',
          date: '1 hour ago',
          highlight: 'Analyzed 2 enrolled students struggling with 1D DP tabulation',
        },
      ],
    },
    weakTopics: [],
  },
  {
    id: 'user-faculty-elena',
    name: 'Dr. Elena Rostova',
    email: 'elena.rostova@stanford.edu',
    password: 'password123',
    avatarInitials: 'ER',
    academicLevel: 'Dean & Academic Director',
    majorOrFocus: 'Biology & Medicine',
    targetGoal: 'Medical Coaching Mastery & Offline Lab Practice Supervision',
    organization: 'Stanford Pre-Med Academy',
    role: 'faculty',
    joinedDate: 'January 2026',
    streakDetails: {
      lastVisitDate: getTodayDateString(),
      lastPracticeDate: getTodayDateString(),
      visitedDates: Array.from({ length: 15 }, (_, i) => getOffsetDateString(i)),
      practicedDates: Array.from({ length: 12 }, (_, i) => getOffsetDateString(i)),
      currentStreak: 15,
      longestStreak: 20,
    },
    stats: {
      studyStreakDays: 15,
      weeklyHoursStudied: 28.0,
      doubtsResolvedCount: 38,
      quizzesCompletedCount: 14,
      averageQuizScore: 96,
      conceptMastery: [
        { subject: 'Biology & Medicine', score: 97, color: '#10b981' },
        { subject: 'Chemistry', score: 93, color: '#f59e0b' },
      ],
      recentActivities: [
        {
          id: 'act-f2',
          type: 'guide',
          title: 'Pre-Med Cohort Audit: Enzyme Kinetics Diagnostics',
          date: 'Yesterday',
          highlight: 'Identified buffer equilibrium calculations needing whiteboard review',
        },
      ],
    },
    weakTopics: [],
  }
];
